# Generated by Django 5.0.7 on 2024-07-16 17:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('time', models.TimeField(default=django.utils.timezone.now)),
                ('day_of_week', models.CharField(blank=True, max_length=9)),
                ('category', models.CharField(choices=[('Schoolwork', 'Schoolwork'), ('Professional', 'Professional'), ('Job', 'Job'), ('Errand', 'Errand')], default='Schoolwork', max_length=50)),
                ('task_description', models.TextField()),
                ('time_taken', models.DurationField(blank=True, null=True)),
                ('expected_proof_num', models.IntegerField(default=1)),
                ('valid_proof_num', models.IntegerField(default=0)),
                ('invalid_proof_num', models.IntegerField(default=0)),
                ('proof_images', models.JSONField(blank=True, default=dict)),
                ('approval_status', models.BooleanField(default=False)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
