# Generated by Django 5.0.7 on 2024-07-16 18:18

import django.db.models.deletion
import proof_approval.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proof_approval', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProofImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=proof_approval.models.user_directory_path)),
                ('validated', models.BooleanField(default=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proof_pics', to='proof_approval.task')),
            ],
        ),
    ]
