# Generated by Django 5.0.7 on 2024-07-31 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proof_approval', '0003_rename_proof_images_task_proof_urls_alter_task_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='proof_urls',
            new_name='proof_dict',
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.date(2024, 7, 31)),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(default=datetime.time(14, 47, 11, 378519)),
        ),
    ]
